name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t registry.heroku.com/wine-crud-app/web .
          docker push registry.heroku.com/wine-crud-app/web

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Configure Heroku environment
        run: |
          heroku config:set PYTHONPATH=/app --app wine-crud-app
          heroku config:set PORT=8000 --app wine-crud-app
          # Check if DATABASE_URL is set
          if ! heroku config:get DATABASE_URL --app wine-crud-app; then
            heroku addons:create heroku-postgresql:mini --app wine-crud-app
          fi

      - name: Release the app
        run: |
          heroku container:release web --app wine-crud-app
          # Wait for app to start
          sleep 10

      - name: Run database migrations
        run: |
          heroku run alembic upgrade head --app wine-crud-app
          # Wait for migrations to complete
          sleep 5

      - name: Run data seeding
        run: |
          heroku run "cd /app && python -m app.seed" --app wine-crud-app

      - name: Verify deployment
        run: |
          echo "Checking application logs..."
          heroku logs --tail --app wine-crud-app &
          sleep 10
          curl -I https://wine-crud-app.herokuapp.com/
